### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by riponbanik** [awslabs/aws-iam-aad#1]
After log into the ec2 as ec2-user, the following errors are shown - 

Import-Module : The specified module 'AWSPowerShell.NetCore' was not loaded beca                                                                                                                                                             use no valid module file was found in any module directory.
At /home/ec2-user/scripts/setup/setup.ps1:26 char:1
+ Import-Module -Name AWSPowerShell.NetCore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (AWSPowerShell.NetCore:String) [I                                                                                                                                                             mport-Module], FileNotFoundException
+ FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.I                                                                                                                                                             mportModuleCommand

**Comment by SepehrCloud** [comment]
This issue is fixed.
